<a href="https://colab.research.google.com/github/harshsrivastava096/Python-Learnings/blob/libraries/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PANDAS**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Here we use pd.Series()

# Basic Series Printing

In [ ]:
a = pd.Series([1,2,3,4,5])
print(a)

0    1
1    2
2    3
3    4
4    5
dtype: int64

# Series with Ranges

In [ ]:
b = pd.Series(np.arange(1,13))
b

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
dtype: int64

#Task: Create a Series with a range of values between 200-250

In [ ]:
c = pd.Series(np.arange(200,251), name = "Listing")
c

0     200
1     201
2     202
3     203
4     204
5     205
6     206
7     207
8     208
9     209
10    210
11    211
12    212
13    213
14    214
15    215
16    216
17    217
18    218
19    219
20    220
21    221
22    222
23    223
24    224
25    225
26    226
27    227
28    228
29    229
30    230
31    231
32    232
33    233
34    234
35    235
36    236
37    237
38    238
39    239
40    240
41    241
42    242
43    243
44    244
45    245
46    246
47    247
48    248
49    249
50    250
Name: Listing, dtype: int64

# Task: Create a Series with a range of values between 340-364, name it as Price

In [ ]:
d = pd.Series(np.arange(340,365), name = "Price")
d

0     340
1     341
2     342
3     343
4     344
5     345
6     346
7     347
8     348
9     349
10    350
11    351
12    352
13    353
14    354
15    355
16    356
17    357
18    358
19    359
20    360
21    361
22    362
23    363
24    364
Name: Price, dtype: int64

In [ ]:
e = pd.Series([1,2,3,4,5],index=['a','b','c','d','e'], name = "Pandas")
e

a    1
b    2
c    3
d    4
e    5
Name: Pandas, dtype: int64

#Task: Create a series with 5 elements and give 5 device name as  index and also  give the name of the series as devices

In [ ]:
f = pd.Series([1,2,3,4,5],index=['Keyboard','Mouse','Monitor','Printer','Scanner'], name = "Devices")
f

Keyboard    1
Mouse       2
Monitor     3
Printer     4
Scanner     5
Name: Devices, dtype: int64

In [ ]:
g = pd.Series([1,2,3,4,5,6,7],index=np.arange(100,701,100), name = "Devices")
g

100    1
200    2
300    3
400    4
500    5
600    6
700    7
Name: Devices, dtype: int64

# Series Creation with Dictionary

In [ ]:
h = pd.Series({'a':1, 'b':2,'c':3}, name = "Dict")
h

a    1
b    2
c    3
Name: Dict, dtype: int64

# Task: Create a Series with Dictionary having 5 Fruits names and keys should be car brand names

In [ ]:
I = pd.Series(data = {
    "BMW": "Apple",
    "Audi": "Banana",
    "Tesla": "Mango",
    "Toyota": "Orange",
    "Ford": "Grapes"
})
I

BMW        Apple
Audi      Banana
Tesla      Mango
Toyota    Orange
Ford      Grapes
dtype: object

In [ ]:
#If the series is created via a dictionary
#then if you change/add the index then it will show the index, however the values will be filled with null values
#Null values in pandas are known as NaN(Not a Number)

J = pd.Series({"a":1,"b":2,"c":3},index=[2.3,4.3,5.3],name="Dict")
J

2.3   NaN
4.3   NaN
5.3   NaN
Name: Dict, dtype: float64

In [ ]:
K=pd.Series(100,index=[1,2,3,4,5,6]) # creating a series with a scalar value
K

# K.dtype
#dtype-> shows the datatype of the column/Series

# K.ndim
#ndim-> gives you the dimensions of the Series

# K.size
#size-> shows the number of elements

# K.shape
#shape-> shows the shape of the Series

# ar.reshape()--> not there in pandas. Cannot convert a Series into different dimensions directly using reshape

1    100
2    100
3    100
4    100
5    100
6    100
dtype: int64

In [ ]:
L=pd.Series(100,index=["a","b","c","d"])
L

a    100
b    100
c    100
d    100
dtype: int64

#Task: Create a series filled with "Hi" and the number of rows should be in between the range of 54-79

---

In [ ]:
M = pd.Series('Hi',index=range(54,80), name = "Hi List")
M

54    Hi
55    Hi
56    Hi
57    Hi
58    Hi
59    Hi
60    Hi
61    Hi
62    Hi
63    Hi
64    Hi
65    Hi
66    Hi
67    Hi
68    Hi
69    Hi
70    Hi
71    Hi
72    Hi
73    Hi
74    Hi
75    Hi
76    Hi
77    Hi
78    Hi
79    Hi
Name: Hi List, dtype: object